version: '3'

services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:rw
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    #networks:
    #  - redis-net

  redis-sentinel-1:
    image: redis:latest
    container_name: redis-sentinel-1
    command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
    volumes:
      - ./sentinel.conf:/etc/redis/sentinel.conf:rw
    #networks:
    #  - redis-net
    depends_on:
      - redis-master

  redis-sentinel-2:
    image: redis:latest
    container_name: redis-sentinel-2
    command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
    volumes:
      - ./sentinel.conf:/etc/redis/sentinel.conf:rw
    #networks:
    #  - redis-net
    depends_on:
      - redis-master

#networks:
#  redis-net:
